#!/system/bin/sh

mount -o remount,rw /system;

var_gps="/system/etc/gps.conf";

sed -i "s/NTP_SERVER[.a-zA-Z\=-\0-5\]*//g" $var_gps;
sed -i "s/-america[.a-zA-Z\=-\0-5\]*//g" $var_gps;
echo "NTP_SERVER=asia.pool.ntp.org" >> $var_gps;
echo "NTP_SERVER=0.asia.pool.ntp.org" >> $var_gps;
echo "NTP_SERVER=1.asia.pool.ntp.org" >> $var_gps;
echo "NTP_SERVER=2.asia.pool.ntp.org" >> $var_gps;
echo "NTP_SERVER=3.asia.pool.ntp.org" >> $var_gps;
