#!/system/xbin/bash

# this number needs to be incremented to roll out a purge to all devices
TIMES_SOME_DINGUS_BROKE_THUMBNAILS=2

current=`getprop persist.vanir.times_some_dingus_broke_thumbnails`
if [ ! $current ] || [ ! "$current" = "$TIMES_SOME_DINGUS_BROKE_THUMBNAILS" ]; then
    logwrapper purgethumbnails
    logwrapper echo "Thumbnails purged to fix somebody's derp in skia - this will only happen once"
    setprop persist.vanir.times_some_dingus_broke_thumbnails $TIMES_SOME_DINGUS_BROKE_THUMBNAILS
fi
